### ISSUE TITLE
duplication of element

### ISSUE THREAD

**Issue by EliorEstrin** [imhardikdesai/Niru-Patel-Boarding-Hostel#2]
### RegardingThe >>  Div class >> subFooterElement 

Both Elements Contain links of Instagram and Facebook.
The purple bottom hides them as well and its duplicates 2 inches down. 

### **Solution**
I suggest to remove them from the upper subFooterElement and keep it on the bottom one (Like in images before.png and after.png).

Current State >> no good
![before](https://user-images.githubusercontent.com/38114330/192413464-f80a263b-c426-47dc-a5e9-640f0689efaf.png)

Desired State >>

![after](https://user-images.githubusercontent.com/38114330/192413463-68e1871e-3cdb-4b15-ab9c-8de8fd6ae3f6.png)

If you find my idea logical feel free to open a pull request for that : )

**Comment by imhardikdesai** [comment]
ok i will assigned you issue.

**Comment by imhardikdesai** [comment]
You don't need to remove that png. You have to just change positions of Purple Button

**Comment by EliorEstrin** [comment]
and what about the fact it is a duplicate element?
Don't you think its better to be removed?
If deleted site wont contain repeating elements one close to the other.

**Comment by imhardikdesai** [comment]
No there is no duplicate png. Both footers are required. You have to change only position of blue button

**Comment by imhardikdesai** [comment]
Thank you for your Contribution you fixed issue very well
